return {
    {
        args = {
            {
                argtype = {
                    f = "./test.tl",
                    typeid = 86742,
                    typename = "integer",
                    x = 24,
                    y = 1,
                },
                f = "./test.tl",
                kind = "argument",
                tk = "x",
                x = 21,
                y = 1,
            },
            {
                argtype = {
                    f = "./test.tl",
                    typeid = 86743,
                    typename = "integer",
                    x = 36,
                    y = 1,
                },
                f = "./test.tl",
                kind = "argument",
                tk = "y",
                x = 33,
                y = 1,
            },
            f = "./test.tl",
            kind = "argument_list",
            tk = "(",
            x = 20,
            xend = 43,
            y = 1,
            yend = 1,
        },
        body = {
            {
                exps = {
                    {
                        e1 = {
                            f = "./test.tl",
                            kind = "variable",
                            tk = "x",
                            x = 12,
                            y = 2,
                        },
                        e2 = {
                            f = "./test.tl",
                            kind = "variable",
                            tk = "y",
                            x = 16,
                            y = 2,
                        },
                        f = "./test.tl",
                        kind = "op",
                        op = {
                            arity = 2,
                            op = "+",
                            prec = 9,
                            x = 14,
                            y = 2,
                        },
                        x = 14,
                        y = 2,
                    },
                    f = "./test.tl",
                    kind = "expression_list",
                    tk = "x",
                    x = 12,
                    xend = 3,
                    y = 2,
                    yend = 3,
                },
                f = "./test.tl",
                kind = "return",
                tk = "return",
                x = 5,
                y = 2,
            },
            f = "./test.tl",
            kind = "statements",
            tk = "return",
            x = 5,
            xend = 3,
            y = 2,
            yend = 3,
        },
        f = "./test.tl",
        kind = "global_function",
        min_arity = 2,
        name = {
            f = "./test.tl",
            kind = "identifier",
            tk = "add",
            x = 17,
            y = 1,
        },
        rets = {
            f = "./test.tl",
            tuple = {
                {
                    f = "./test.tl",
                    typeid = 86745,
                    typename = "integer",
                    x = 46,
                    y = 1,
                },
            },
            typeid = 86744,
            typename = "tuple",
            x = 44,
            y = 1,
        },
        tk = "function",
        x = 8,
        xend = 3,
        y = 1,
        yend = 3,
    },
    f = "./test.tl",
    kind = "statements",
    tk = "global",
    x = 1,
    xend = 5,
    y = 1,
    yend = 4,
}
